name: Android CI


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8      
    - name: Installing libraries
      run: | 
        sudo apt update
        sudo apt install -y curl wget git zip unzip tree
    - name: Downloading and installing android build tools
      run: |
        wget https://github.com/ksverchkov/Abt/releases/download/tag/abt.zip
        unzip abt.zip
        cp -r licenses app/
        rm -rf abt.zip
        rm -rf *.apk
    - name: Use chmod to set permissions
      run: chmod a=rwx ./gradlew
    - name: Build app with Gradle
      run: ./gradlew build :app:build
    - name: List tree
      run: tree app/build/
    - name: Upload release
      run: |
        appname=$(date  '+%F_%T.apk')
        cp app/build/output/app-debug.apk $appname
        git add $appname
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Git create
      run: git config --global user.email "builtbot@bot.com"
    - name: Github Identify
      run: git config --global user.name "Build Bot"
    - name: Git commit
      run: git commit -m 'New release created'
    - name: Git Push
      run: |
          git remote set-url origin https://ksverchkov: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@github.com/ksverchkov/AndroidBuildTemplate.git
          git push -u origin main
      
